import Head from "next/head";
import dogs from "../data/dogs";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Perro app</h1>

        <section>
          <ul>
            {dogs.map((dog) => (
              <li>
                <Link key={dog.id} href={`/dog/${dog.id}`}>
                  {dog.name}
                </Link>{" "}
                <br />
                {dog.breed}
              </li>
            ))}
          </ul>
        </section>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
